---
- name: Install haproxy (deb)
  when: ansible_os_family == 'Debian'
  apt:
    name: haproxy
    state: present

- name: Enable haproxy service
  service:
    name: haproxy
    enabled: yes
    state: started

- name: Template haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy
